import { Cinzel } from "next/font/google";
import "./globals.css";
import MainNav from "./Components/MainNav";
import Header from "./Components/Header";
import PageTransition from "./Components/PageTransition";
import RectangleTransition from "./Components/RectangleTransition";

const cinzel = Cinzel({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"], // full range
  variable: "--font-cinzel",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`
         ${cinzel.variable}
        h-full antialiased overflow-hidden relative`}
    >
      <body className="min-h-full flex flex-col">
        <RectangleTransition />
        <PageTransition>
          <div className="flex">
            <div className="text-[18px] hidden 2xl:flex  w-[285px] h-screen bg-secondary justify-center items-center ">
              <MainNav />
            </div>
            <div className="w-full  px-[15px] mx-auto max-w-[1130px] h-screen">
              <header>
                <Header />
              </header>
              <div>{children}</div>
            </div>
          </div>
        </PageTransition>
      </body>
    </html>
  );
}
