import { Bangers } from "next/font/google";
import "./globals.css";
import MainNav from "./Components/MainNav";
import Header from "./Components/Header";

const bangers = Bangers({
  subsets: ["latin"],
  weight: ["400"], // Bangers only has 400 weight
  variable: "--font-bangers",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`
         ${bangers.variable}
        h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="flex">
          <div className="text-2xl hidden 2xl:flex  w-[285px] h-screen bg-secondary">
            <MainNav />
          </div>
          <div className="w-full bg-pink-50/10 px-[15px] mx-auto max-w-[1130px]">
            <header>
              <Header />
            </header>
            <div>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
